version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: almacen-nginx
    ports:
      - "80:80"  # Exponer puerto 80
    volumes:
      - ./frontend:/var/www/frontend
      - ./backend:/var/www/backend
      - ./docker/nginx:/etc/nginx/conf.d  # Configuración personalizada de nginx
    depends_on:
      - php
    networks:
      - almacen-network
      

  php:
    build:
      context: ./docker/php
    container_name: almacen-php
    volumes:
      - ./backend:/var/www/html
      - ./backend/firmas:/var/www/html/firmas
    ports:
      - "9000:9000"  # Exponer PHP-FPM en el puerto 9000
    networks:
      - almacen-network

  mariadb:
    image: mariadb:11
    container_name: almacen-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: almacen
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - almacen-network

networks:
  almacen-network:

volumes:
  mariadb_data: