server {
    listen 80;
    server_name localhost;

    # ======================
    # FRONTEND
    # ======================
    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # ======================
    # API (PHP)
    # ======================
    location /api {
        include fastcgi_params;

        fastcgi_pass almacen-php:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param PATH_INFO $uri;
    }

    # ======================
    # PHP directo (por si acaso)
    # ======================
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass almacen-php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}