server {
    listen 80;
    server_name localhost;

    # ======================
    # FRONTEND
    # ======================
    root /var/www/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # ======================
    # API (PHP)
    # ======================
    location ~ \.php$ {
        root /var/www/html;  # 👈 backend

        fastcgi_pass php:9000;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }

    # ======================
    # PHP directo (por si acaso)
    # ======================
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass almacen-php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}